controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index

item_index:
    path: item/index
    controller: App\Controller\ItemController::index
